### ISSUE TITLE
安装的时候卡住了

### ISSUE THREAD

**Issue by spicybar7** [0x727/BugRepoter_0x727#5]
点击下一步没有反应

**Comment by xz-zone** [comment]
是不是数据库密码错误，你是docker环境还是？

**Comment by spicybar7** [comment]
自己创了一个ubuntu的虚拟机，安装的时候，到了第二步，填了数据库名，密码啥的之后点击下一步没反应。

**Comment by xz-zone** [comment]
你好，你把错误打开查看下什么报错。在更目录的index.php







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "0x727/BugRepoter_0x727"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [0x727/BugRepoter_0x727] 安装的时候卡住了 (Issue #5)





 
我是配好基础环境后，输入url：http://域名/index.php?m=Install&amp;a=index，第一个显示的是”url参数错误“，第二个显示的是”请安装应用“，然后再才是安装界面，然后点下一步，正常输入数据库信息后，再点下一步没反应，我故意把其中一个信息空出来，倒是有错误提示。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xz-zone** [comment]
已经解决了报错问题，请更新到最新版本。数据库名字要用英文。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "0x727/BugRepoter_0x727"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月21日(星期四) 中午12:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [0x727/BugRepoter_0x727] 安装的时候卡住了 (Issue #5)





 
报错信息（我的pod_mysql拓展打开了）：Fatal error: Uncaught PDOException: could not find driver in /var/www/html/BugRepoter_0x727/config/function.php:552 Stack trace: #0 /var/www/html/BugRepoter_0x727/config/function.php(552): PDO-&gt;__construct() #1 /var/www/html/BugRepoter_0x727/index/controllers/InstallControllers.php(27): try_mysql() #2 /var/www/html/BugRepoter_0x727/index.php(184): InstallControllers-&gt;index() #3 {main} thrown in /var/www/html/BugRepoter_0x727/config/function.php on line 552
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by spicybar7** [comment]
感谢您及时回复我的问题，但还是这一步还是没跨过去。现在报错信息是：连接失败！但是我用另外的电脑，同样的信息是可以连接进这个数据库的。（数据库名是英文：BugTest，用户名也是英文：BugT）
